export default {
    style:{
        ListTop:{
            margin:10
        },
        ListAddBtn:{
            marginBottom:10,
            width:100
        },
        ListTableTopRow:{
            lineHeight:"40px",
            backgroundColor:"#f1f1f2",
            textAlign:"center",
            color:"#333"
        },
        ListSearchTable:{
            backgroundColor:"#fafaf7",
            paddingTop:10,
            margin:"0px 10px",
        },
        ListTable:{
            backgroundColor:"#fafaf7",
            padding:"10px 10px 20px 10px",
        },
        AddBottom:{
            height:"60px",
            backgroundColor:"#fafaf7",
            position:"fixed",
            bottom:"0px",
            width:"100%",
            boxShadow: "0px -5px 5px #E1E0DE"
        },
        SubmitBtn:{
            width:100,
            marginRight:"15px",
            float:"right",
            marginTop:"15px"
        },
        CancelBtn:{
            width:100,
            float:"left",
            marginTop:"15px",
            marginLeft:"15px"
        },
        EmptyRow:{
            height:"100px"
        },
        hStyle:{
            backgroundColor:"#fafaf7",
            textAlign:"center",
            fontSize:"18px",
            lineHeight:"36px",
            color:"rgb(80,172,226)",
            position:"absolute",
            top:10,
            left:"44%"
        },
        FormStyle:{
            backgroundColor:"#fafaf7",
            margin:"10px",
            padding:"10px",
            position:"relative",
        },
        Pagination:{
            textAlign:"right",
            margin:20
        },

    }
}